Fix for invalid backend type
sodafoundation/multi-cloud pull request #1151
Opened 2020-11-17 14:46 UTC by vineela1999

**What type of PR is this?**
> /kind bug fix

**What this PR does / why we need it**:
when a create backend request is sent, type of the backend is to be verified to proceed.
**Which issue(s) this PR fixes**:

Fixes #1107 

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:
 when an invalid backend type is given:
![image](https://user-images.githubusercontent.com/65920384/99404066-31b41380-2911-11eb-855b-a62dd28dd07a.png)
![image](https://user-images.githubusercontent.com/65920384/99404107-3bd61200-2911-11eb-8ecd-7c859e353544.png)
When a valid backend type is given:
![Screenshot from 2020-11-17 18-42-34](https://user-images.githubusercontent.com/65920384/99404249-6b851a00-2911-11eb-8be3-5cb1f5ac3b55.png)
![Screenshot from 2020-11-17 18-44-23](https://user-images.githubusercontent.com/65920384/99404460-aa1ad480-2911-11eb-9bb0-a05b6b917c90.png)

**Special notes for your reviewer**:

2020-11-18 11:03 UTC, himanshuvar commented on api/pkg/backend/service.go
> +		log.Errorf("Failed to create backend: %v\n", err)
Same as above

2020-11-18 11:06 UTC, himanshuvar commented on api/pkg/backend/service.go
> +func typeExists(slice []*backend.TypeDetail, inputType string) (int, bool) {
Do we need to return two parameters, Are we using index?
Only boolean is not sufficient?

2020-11-18 11:09 UTC, himanshuvar commented on api/pkg/backend/service.go
> +	response.WriteEntity(storageTypes)
Do we need to handle Exception/Error before writing to response

2020-11-18 11:11 UTC, himanshuvar commented on api/pkg/backend/service.go
> +	storageTypes,_:= s.listStorageType(ctx,request,response)
Please handle Exception/Error, there might be a nil pointer

2020-11-18 17:21 UTC, vineela1999 commented
@himanshuvar code rework done

2020-11-19 03:43 UTC, himanshuvar commented on api/pkg/backend/service.go
> +		log.Errorf("failed to create backend: %v\n", err)
failed to list backend?

2020-11-19 03:44 UTC, himanshuvar commented on api/pkg/backend/service.go
> +	log.Info("Create backend successfully.")
Created was appropriate

2020-11-19 03:46 UTC, himanshuvar requested changes
Minor Typo comments

2020-11-19 04:22 UTC, kumarashit commented on api/pkg/backend/service.go
> +		if item.Name == inputType {
Put a debug level log message before returning

2020-11-19 05:29 UTC, vineela1999 commented
@himanshuvar @kumarashit 
changes done

2020-11-19 06:15 UTC, kumarashit approved these changes
LGTM

2020-11-23 11:37 UTC, wisererik requested changes
it's better to format code

2020-11-23 11:37 UTC, wisererik commented on api/pkg/backend/service.go
> +	storageTypes,err:= s.listStorageType(ctx,request,response)
need space between , and err

2020-11-23 11:37 UTC, wisererik commented on api/pkg/backend/service.go
> +	storageTypes,err:=s.listStorageType(ctx,request,response)
storageTypes,err:=s.listStorageType(ctx,request,response) -> storageTypes, err := s.listStorageType(ctx, request, response)

2020-11-23 11:56 UTC, vineela1999 commented
@wisererik done with change

2020-11-26 06:10 UTC, wisererik approved these changes

2020-11-26 06:10 UTC, merged